# Copyright 2016 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
project_name: http_blaster
env:
  - GO111MODULE=on
  - GOPROXY=goproxy.devops.iguazeng.com
before:
  hooks:
    - go mod download
builds:
  - id: http_blaster
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: http_blaster
    ldflags:
      - -s -w -X main.AppVersion={{ .Version }}
  - id: http_blaster_latest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: http_blaster
    ldflags:
      - -s -w -X main.AppVersion={{ .Version }}
archives:
  - id: http_blaster
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      amd64: x86_64
    builds:
      - http_blaster
    allow_different_binary_count: true
  - id: http_blaster_latest
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      amd64: x86_64
    builds:
      - http_blaster_latest
    allow_different_binary_count: true
release:
  ids:
    - http_blaster
artifactories:
  - name: iguazio
    target: https://artifactory.iguazeng.com/artifactory/iguazio_naipi/{{ .ProjectName }}/{{ .Version }}/
    mode: binary
    checksum: true
    ids:
      - http_blaster
  - name: naipi
    target: https://artifactory.iguazeng.com/artifactory/iguazio_naipi/{{ .ProjectName }}/
    mode: binary
    checksum: true
    ids:
      - http_blaster_latest
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  disable: false
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
